-- 占位迁移，建立最小表结构；后续可扩展会话、片段翻译等
CREATE TABLE IF NOT EXISTS si_meta (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
